//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""e77b76a9-19e4-4223-88da-2ab9fb4a3369"",
            ""actions"": [
                {
                    ""name"": ""ShootTop"",
                    ""type"": ""Button"",
                    ""id"": ""577aee48-3cb8-44b7-be78-650977f249ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootBottom"",
                    ""type"": ""Button"",
                    ""id"": ""855c7d52-0f8f-4035-ab63-cea01f3508c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bffb55a5-c5bd-4350-99cf-824a31e41578"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5e07866-80bd-45fa-8808-26572848faf4"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootBottom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ShootTop = m_Player.FindAction("ShootTop", throwIfNotFound: true);
        m_Player_ShootBottom = m_Player.FindAction("ShootBottom", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_ShootTop;
    private readonly InputAction m_Player_ShootBottom;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShootTop => m_Wrapper.m_Player_ShootTop;
        public InputAction @ShootBottom => m_Wrapper.m_Player_ShootBottom;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @ShootTop.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootTop;
                @ShootTop.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootTop;
                @ShootTop.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootTop;
                @ShootBottom.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootBottom;
                @ShootBottom.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootBottom;
                @ShootBottom.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootBottom;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ShootTop.started += instance.OnShootTop;
                @ShootTop.performed += instance.OnShootTop;
                @ShootTop.canceled += instance.OnShootTop;
                @ShootBottom.started += instance.OnShootBottom;
                @ShootBottom.performed += instance.OnShootBottom;
                @ShootBottom.canceled += instance.OnShootBottom;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnShootTop(InputAction.CallbackContext context);
        void OnShootBottom(InputAction.CallbackContext context);
    }
}
